import { GameLevel } from './types/progress';

export const GAME_LEVELS: GameLevel[] = [
  {
    id: 'letter-hunt',
    title: 'Letter Hunt',
    description: 'Find and identify Malayalam letters hidden in a vibrant scene.',
    href: '/games/letter-hunt',
  },
  {
    id: 'whack-a-vowel',
    title: 'Whack-A-Vowel',
    description: 'Quickly tap on the correct Malayalam vowels as they appear.',
    href: '/games/whack-a-vowel',
    prerequisite: 'letter-hunt',
  },
  {
    id: 'consonant-runner',
    title: 'Consonant Runner',
    description: 'Collect Malayalam consonants in a rhythm-based arcade challenge.',
    href: '/consonant-runner',
    prerequisite: 'whack-a-vowel',
  },
  {
    id: 'emoji-word-match',
    title: 'Emoji-to-Word Match',
    description: 'Match emojis with their corresponding Malayalam words.',
    href: '/games/emoji-word-match',
    prerequisite: 'consonant-runner',
  },
  {
    id: 'word-jigsaw',
    title: 'Word Jigsaw',
    description: 'Arrange letter pieces to form complete Malayalam words.',
    href: '/games/word-jigsaw',
    prerequisite: 'emoji-word-match',
  },
  {
    id: 'fill-in-the-blanks',
    title: 'Fill in the Blanks',
    description: 'Complete Malayalam sentences by filling in the missing words.',
    href: '/games/fill-in-the-blanks',
    prerequisite: 'word-jigsaw',
  },
  {
    id: 'flashcard-battle',
    title: 'Flashcard Battle',
    description: 'Test your vocabulary recall in a fast-paced flashcard challenge.',
    href: '/games/flashcard-battle',
    prerequisite: 'fill-in-the-blanks',
  },
  {
    id: 'memory-match',
    title: 'Memory Match',
    description: 'Find pairs of matching Malayalam words and their meanings.',
    href: '/games/memory-match',
    prerequisite: 'flashcard-battle',
  },
  {
    id: 'sound-match',
    title: 'Sound Match',
    description: 'Match Malayalam words to their correct pronunciations.',
    href: '/games/sound-match',
    prerequisite: 'memory-match',
  },
  {
    id: 'pronunciation-challenge',
    title: 'Pronunciation Challenge',
    description: 'Practice and perfect your Malayalam pronunciation.',
    href: '/games/pronunciation-challenge',
    prerequisite: 'sound-match',
  },
  {
    id: 'speed-typing-race',
    title: 'Speed Typing Race',
    description: 'Type Malayalam words quickly before the timer runs out.',
    href: '/games/speed-typing-race',
    prerequisite: 'pronunciation-challenge',
  },
  {
    id: 'magic-tracing',
    title: 'Magic Tracing',
    description: 'Learn to write Malayalam letters and words by tracing.',
    href: '/games/magic-tracing',
    prerequisite: 'speed-typing-race',
  },
  {
    id: 'maveli-game',
    title: 'Maveli\'s Onam Adventure',
    description: 'Embark on a cultural adventure with King Mahabali during Onam.',
    href: '/games/maveli-game',
    prerequisite: 'magic-tracing',
  },
  {
    id: 'festival-quest',
    title: 'Festival Quest',
    description: 'Explore Malayalam festivals and traditions through interactive quests.',
    href: '/games/festival-quest',
    prerequisite: 'maveli-game',
  },
  {
    id: 'quiz-battle',
    title: 'Quiz Battle',
    description: 'Challenge your friends in a head-to-head Malayalam knowledge quiz.',
    href: '/games/quiz-battle',
    prerequisite: 'festival-quest',
  },
  {
    id: 'cultural-trivia',
    title: 'Cultural Trivia Show',
    description: 'Test your knowledge of Malayalam culture in a quiz show format.',
    href: '/games/cultural-trivia',
    prerequisite: 'quiz-battle',
  },
  {
    id: 'voice-command-game',
    title: 'Voice Command Game',
    description: 'Control characters by speaking Malayalam words aloud.',
    href: '/games/voice-command-game',
    prerequisite: 'cultural-trivia',
  },
];