import { GameLevel } from './types/progress';

export const GAME_LEVELS: GameLevel[] = [
  {
    id: 'letter-hunt',
    title: 'Letter Hunt',
    description: 'Find and identify Malayalam letters hidden in a vibrant scene.',
    href: '/play?id=letter-hunt',
  },
  {
    id: 'consonant-adventure',
    title: 'Consonant Adventure Game',
    description: 'Embark on a cultural adventure to collect all the consonants.',
    href: '/play?id=consonant-adventure',
    prerequisite: 'letter-hunt',
  },
  {
    id: 'consonant-space-runner',
    title: 'Consonant Space Runner',
    description: 'Collect Malayalam consonants in a rhythm-based arcade challenge.',
    href: '/play?id=consonant-space-runner',
    prerequisite: 'consonant-adventure',
  },
  {
    id: 'magic-tracing',
    title: 'Magic Tracing',
    description: 'Learn to write Malayalam letters and words by tracing.',
    href: '/play?id=magic-tracing',
    prerequisite: 'consonant-space-runner',
  },
  {
    id: 'memory-match',
    title: 'Memory Match',
    description: 'Find pairs of matching Malayalam words and their meanings.',
    href: '/play?id=memory-match',
    prerequisite: 'magic-tracing',
  },
  {
    id: 'whack-a-vowel',
    title: 'Whack-A-Vowel',
    description: 'Quickly tap on the correct Malayalam vowels as they appear.',
    href: '/play?id=whack-a-vowel',
    prerequisite: 'memory-match',
  },
  {
    id: 'pookkalam-coloring',
    title: 'Pookalam Coloring',
    description: 'Learn Malayalam colors by coloring a Pookalam with your voice.',
    href: '/play?id=pookkalam-coloring',
    prerequisite: 'whack-a-vowel',
  },
  {
    id: 'mahjong-game',
    title: '3D Mahjong',
    description: 'Match Malayalam letters in a 3D Mahjong game.',
    href: '/play?id=mahjong-game',
    prerequisite: 'pookkalam-coloring',
  },
  {
    id: 'flashcard-battle',
    title: 'Flashcard Battle',
    description: 'Test your vocabulary recall in a fast-paced flashcard challenge.',
    href: '/play?id=flashcard-battle',
    prerequisite: 'mahjong-game',
  },
  {
    id: 'word-formation',
    title: 'Word Formation',
    description: 'Form valid Malayalam words from a given set of letters.',
    href: '/play?id=word-formation',
    prerequisite: 'flashcard-battle',
  },
  {
    id: 'word-jigsaw',
    title: 'Word Jigsaw',
    description: 'Arrange letter pieces to form complete Malayalam words.',
    href: '/play?id=word-jigsaw',
    prerequisite: 'word-formation',
  },
  {
    id: 'picture-prompt',
    title: 'Picture Prompt Game',
    description: 'Say the words that describe the picture.',
    href: '/play?id=picture-prompt-voice',
    prerequisite: 'word-jigsaw',
  },
  {
    id: 'pronunciation-challenge',
    title: 'Pronunciation Challenge',
    description: 'Practice and perfect your Malayalam pronunciation.',
    href: '/play?id=pronunciation-challenge',
    prerequisite: 'picture-prompt-voice',
  },
  {
    id: 'voice-command-game',
    title: 'Voice Command Game',
    description: 'Control characters by speaking Malayalam words aloud.',
    href: '/play?id=voice-command-game',
    prerequisite: 'pronunciation-challenge',
  },
  {
    id: 'sound-match',
    title: 'Sound Match',
    description: 'Match Malayalam words to their correct pronunciations.',
    href: '/play?id=sound-match',
    prerequisite: 'voice-command-game',
  },
  {
    id: 'speed-typing',
    title: 'Speed Typing Race',
    description: 'Type Malayalam words quickly before the timer runs out.',
    href: '/play?id=speed-typing',
    prerequisite: 'sound-match',
  },
  {
    id: 'emoji-word-match',
    title: 'Emoji-to-Word Match',
    description: 'Match emojis with their corresponding Malayalam words.',
    href: '/play?id=emoji-word-match',
    prerequisite: 'speed-typing',
  },
  {
    id: 'fill-in-the-blanks',
    title: 'Fill in the Blanks',
    description: 'Complete Malayalam sentences by filling in the missing words.',
    href: '/play?id=fill-in-the-blanks',
    prerequisite: 'emoji-word-match',
  },
  {
    id: 'quiz-battle',
    title: 'Quiz Battle',
    description: 'Challenge your friends in a head-to-head Malayalam knowledge quiz.',
    href: '/play?id=quiz-battle',
    prerequisite: 'fill-in-the-blanks',
  },
  {
    id: 'festival-quest',
    title: 'Festival Quest',
    description: 'Explore Malayalam festivals and traditions through interactive quests.',
    href: '/play?id=festival-quest',
    prerequisite: 'quiz-battle',
  },
  {
    id: 'cultural-trivia',
    title: 'Cultural Trivia Show',
    description: 'Test your knowledge of Malayalam culture in a quiz show format.',
    href: '/play?id=cultural-trivia',
    prerequisite: 'festival-quest',
  },
  {
    id: 'word-search',
    title: 'Word Search',
    description: 'Find hidden Malayalam words in a grid of letters.',
    href: '/play?id=word-search',
    prerequisite: 'cultural-trivia',
  },
  {
    id: 'crossword-puzzle',
    title: 'Crossword Puzzle',
    description: 'Solve Malayalam crossword puzzles.',
    href: '/play?id=crossword-puzzle',
    prerequisite: 'word-search',
  },
  {
    id: 'malayalam-scrabble',
    title: 'Malayalam Scrabble',
    description: 'Play Scrabble with Malayalam letters.',
    href: '/play?id=malayalam-scrabble',
    prerequisite: 'crossword-puzzle',
  },
  {
    id: 'wordfind',
    title: 'WordFind',
    description: 'Find Malayalam words in a 6x6 grid using a clock dial letter selection.',
    href: '/play?id=wordfind',
    prerequisite: 'malayalam-scrabble',
  },
  {
    id: 'spin-a-wheel',
    title: 'Spin a Wheel',
    description: 'Test your luck and learn consonants with a spin of the wheel.',
    href: '/games/spin-a-wheel',
    prerequisite: 'wordfind',
  },
  {
    id: 'consonant-arrow-game',
    title: 'Consonant Arrow Game',
    description: 'Aim and shoot consonants with a bow and arrow.',
    href: '/play?id=consonant-arrow-game',
    prerequisite: 'spin-a-wheel',
  },
  {
    id: 'malayalam-dance-simon',
    title: 'Malayalam Dance Simon',
    description: 'Students watch traditional Kerala dance movements paired with Malayalam words/phrases, then repeat the sequence from memory.',
    href: '/games/malayalam-dance-simon',
    prerequisite: 'consonant-arrow-game',
  },
  {
    id: 'fruit-catch-vocabulary',
    title: 'Fruit Catch Vocabulary',
    description: 'Items fall from the top with Malayalam labels; students drag them into correct category baskets while learning food/object vocabulary.',
    href: '/games/fruit-catch-vocabulary',
    prerequisite: 'malayalam-dance-simon',
  },
  {
    id: 'rhythm-rhyme-drummer',
    title: 'Rhythm & Rhyme Drummer',
    description: 'Tap drums to the rhythm of Malayalam poems/songs, matching syllable patterns to learn prosody.',
    href: '/games/rhythm-rhyme-drummer',
    prerequisite: 'fruit-catch-vocabulary',
  },
  {
    id: 'choose-your-own-adventure-story',
    title: 'Choose Your Own Adventure Story',
    description: 'Interactive branching stories in Malayalam where choices affect the outcome, teaching reading comprehension and decision vocabulary.',
    href: '/games/choose-your-own-adventure-story',
    prerequisite: 'rhythm-rhyme-drummer',
  },
  {
    id: 'comic-strip-creator',
    title: 'Comic Strip Creator',
    description: 'Students arrange panels and add Malayalam dialogue bubbles to create stories, learning sentence structure.',
    href: '/games/comic-strip-creator',
    prerequisite: 'choose-your-own-adventure-story',
  },
  {
    id: 'mystery-detective-game',
    title: 'Mystery Detective Game',
    description: 'Solve mysteries by reading Malayalam clues, interviewing virtual characters, and piecing together evidence.',
    href: '/games/mystery-detective-game',
    prerequisite: 'comic-strip-creator',
  },
  {
    id: 'puppet-show-theater',
    title: 'Puppet Show Theater',
    description: 'Control virtual puppets with Malayalam voice commands to perform traditional Kerala stories.',
    href: '/games/puppet-show-theater',
    prerequisite: 'mystery-detective-game',
  },
  {
    id: 'recipe-master-chef',
    title: 'Recipe Master Chef',
    description: 'Follow Malayalam instructions to prepare virtual Kerala dishes, learning cooking vocabulary and imperative verbs.',
    href: '/games/recipe-master-chef',
    prerequisite: 'puppet-show-theater',
  },
  {
    id: 'malayalam-mad-libs',
    title: 'Malayalam Mad Libs',
    description: 'Fill in missing words (nouns, verbs, adjectives) to create funny stories while learning parts of speech.',
    href: '/games/malayalam-mad-libs',
    prerequisite: 'recipe-master-chef',
  },
  {
    id: 'word-chain-challenge',
    title: 'Word Chain Challenge',
    description: 'Last letter of one word must be the first letter of the next (Malayalam word chain game - അക്ഷരശ്ലോകം style).',
    href: '/games/word-chain-challenge',
    prerequisite: 'malayalam-mad-libs',
  },
  {
    id: 'grammar-sorting-factory',
    title: 'Grammar Sorting Factory',
    description: 'Words arrive on conveyor belts; sort them by grammatical gender, tense, or word type.',
    href: '/games/grammar-sorting-factory',
    prerequisite: 'word-chain-challenge',
  },
  {
    id: 'sentence-builder-blocks',
    title: 'Sentence Builder Blocks',
    description: 'Drag and stack word blocks in correct order to build grammatically correct Malayalam sentences.',
    href: '/games/sentence-builder-blocks',
    prerequisite: 'grammar-sorting-factory',
  },
  {
    id: 'virtual-onam-market',
    title: 'Virtual Onam Market',
    description: 'Shop in a virtual market, haggling and conversing in Malayalam to buy items for Onam celebrations.',
    href: '/games/virtual-onam-market',
    prerequisite: 'sentence-builder-blocks',
  },
  {
    id: 'boat-race-commentator',
    title: 'Boat Race Commentator',
    description: 'Narrate a virtual Vallam Kali (snake boat race) using Malayalam sports vocabulary.',
    href: '/games/boat-race-commentator',
    prerequisite: 'virtual-onam-market',
  },
  {
    id: 'kathakali-face-painting',
    title: 'Kathakali Face Painting',
    description: 'Learn color words and facial feature vocabulary while virtually painting Kathakali makeup.',
    href: '/games/kathakali-face-painting',
    prerequisite: 'boat-race-commentator',
  },
  {
    id: 'whisper-chain-challenge',
    title: 'Whisper Chain Challenge',
    description: 'Listen to Malayalam phrases and type what you hear (like telephone game) to improve listening skills.',
    href: '/games/whisper-chain-challenge',
    prerequisite: 'kathakali-face-painting',
  },
  {
    id: 'soundscape-explorer',
    title: 'Soundscape Explorer',
    description: 'Explore virtual Kerala environments (beach, backwaters, temple) clicking objects to hear their Malayalam names and sounds.',
    href: '/games/soundscape-explorer',
    prerequisite: 'whisper-chain-challenge',
  },
  {
    id: 'vowel-order-find',
    title: 'Vowel Order Find',
    description: 'Click Malayalam vowels in correct order in Learn Mode, then find them in random order in Play Mode.',
    href: '/games/vowel-order-find',
    prerequisite: 'soundscape-explorer',
  },
  {
    id: 'malayalam-pictionary',
    title: 'Malayalam Pictionary',
    description: 'Draw pictures while others guess the Malayalam word (multiplayer or AI guessing).',
    href: '/games/malayalam-pictionary',
    prerequisite: 'dialect-detective',
  },
  {
    id: 'word-auction-house',
    title: 'Word Auction House',
    description: 'Bid on words using points, then use purchased words to construct the longest/best sentence.',
    href: '/games/word-auction-house',
    prerequisite: 'malayalam-pictionary',
  },
  {
    id: 'translation-relay-race',
    title: 'Translation Relay Race',
    description: 'Teams race to translate sentences from English to Malayalam or vice versa.',
    href: '/games/translation-relay-race',
    prerequisite: 'word-auction-house',
  },
  {
    id: 'room-label-scanner',
    title: 'Room Label Scanner',
    description: 'Virtual "scanner" mode where students point at objects and label them with Malayalam stickers in their environment.',
    href: '/games/room-label-scanner',
    prerequisite: 'translation-relay-race',
  },
  {
    id: 'treasure-map-navigator',
    title: 'Treasure Map Navigator',
    description: 'Follow Malayalam direction instructions (left/right, north/south) to find hidden treasures on a map.',
    href: '/games/treasure-map-navigator',
    prerequisite: 'room-label-scanner',
  },
  {
    id: 'consonant-find',
    title: 'Consonant Find',
    description: 'A series of games to help you master Malayalam consonants.',
    href: '/games/consonant-find', // This should be a menu page
    prerequisite: 'treasure-map-navigator',
    sublevels: [
      {
        id: 'find-cat-mom',
        title: 'Find Cat Mom',
        description: 'Find the consonants in the correct order.',
        href: '/play?id=find-cat-mom',
        prerequisite: 'consonant-find',
      },
      {
        id: 'consonant-bowling-game',
        title: 'Bowling Game',
        description: 'Knock down bowling pins with Malayalam consonants in the correct order.',
        href: '/games/consonant-bowling',
        prerequisite: 'consonant-order-find-lvl1',
      },
      {
        id: 'consonant-christmas-tree',
        title: 'Christmas Tree',
        description: 'Decorate the Christmas tree by shooting the correct consonants.',
        href: '/play?id=consonant-christmas-tree',
        prerequisite: 'consonant-bowling-game',
      },
      {
        id: 'consonant-flower-bloom',
        title: 'Consonant Flower Bloom',
        description: 'Make the flowers bloom by finding the correct consonants.',
        href: '/play?id=consonant-flower-bloom',
        prerequisite: 'consonant-christmas-tree',
      },
      {
        id: 'consonant-house',
        title: 'Consonant House',
        description: 'Build a house by finding the correct consonants.',
        href: '/play?id=consonant-house',
        prerequisite: 'consonant-flower-bloom',
      },
      {
        id: 'consonant-hornbill',
        title: 'Consonant Hornbill',
        description: 'Connect the dots to draw the Great Hornbill.',
        href: '/play?id=consonant-hornbill',
        prerequisite: 'consonant-house',
      },
    ],
  },
];