import { GameLevel } from './types/progress';

export const GAME_LEVELS: GameLevel[] = [
  {
    id: 'letter-hunt',
    title: 'Letter Hunt',
    description: 'Find and identify Malayalam letters hidden in a vibrant scene.',
    href: '/play?id=letter-hunt',
  },
  {
    id: 'consonant-adventure',
    title: 'Consonant Adventure Game',
    description: 'Embark on a cultural adventure to collect all the consonants.',
    href: '/play?id=consonant-adventure',
    prerequisite: 'letter-hunt',
  },
  {
    id: 'consonant-space-runner',
    title: 'Consonant Space Runner',
    description: 'Collect Malayalam consonants in a rhythm-based arcade challenge.',
    href: '/play?id=consonant-space-runner',
    prerequisite: 'consonant-adventure',
  },
  {
    id: 'magic-tracing',
    title: 'Magic Tracing',
    description: 'Learn to write Malayalam letters and words by tracing.',
    href: '/play?id=magic-tracing',
    prerequisite: 'consonant-space-runner',
  },
  {
    id: 'memory-match',
    title: 'Memory Match',
    description: 'Find pairs of matching Malayalam words and their meanings.',
    href: '/play?id=memory-match',
    prerequisite: 'magic-tracing',
  },
  {
    id: 'whack-a-vowel',
    title: 'Whack-A-Vowel',
    description: 'Quickly tap on the correct Malayalam vowels as they appear.',
    href: '/play?id=whack-a-vowel',
    prerequisite: 'memory-match',
  },
  {
    id: 'pookkalam-coloring',
    title: 'Pookalam Coloring',
    description: 'Learn Malayalam colors by coloring a Pookalam with your voice.',
    href: '/play?id=pookkalam-coloring',
    prerequisite: 'whack-a-vowel',
  },
  {
    id: 'mahjong-game',
    title: '3D Mahjong',
    description: 'Match Malayalam letters in a 3D Mahjong game.',
    href: '/play?id=mahjong-game',
    prerequisite: 'pookkalam-coloring',
  },
  {
    id: 'flashcard-battle',
    title: 'Flashcard Battle',
    description: 'Test your vocabulary recall in a fast-paced flashcard challenge.',
    href: '/play?id=flashcard-battle',
    prerequisite: 'mahjong-game',
  },
  {
    id: 'word-formation',
    title: 'Word Formation',
    description: 'Form valid Malayalam words from a given set of letters.',
    href: '/play?id=word-formation',
    prerequisite: 'flashcard-battle',
  },
  {
    id: 'word-jigsaw',
    title: 'Word Jigsaw',
    description: 'Arrange letter pieces to form complete Malayalam words.',
    href: '/play?id=word-jigsaw',
    prerequisite: 'word-formation',
  },
  {
    id: 'picture-prompt',
    title: 'Picture Prompt Game',
    description: 'Say the words that describe the picture.',
    href: '/play?id=picture-prompt-voice',
    prerequisite: 'word-jigsaw',
  },
  {
    id: 'pronunciation-challenge',
    title: 'Pronunciation Challenge',
    description: 'Practice and perfect your Malayalam pronunciation.',
    href: '/play?id=pronunciation-challenge',
    prerequisite: 'picture-prompt-voice',
  },
  {
    id: 'voice-command-game',
    title: 'Voice Command Game',
    description: 'Control characters by speaking Malayalam words aloud.',
    href: '/play?id=voice-command-game',
    prerequisite: 'pronunciation-challenge',
  },
  {
    id: 'sound-match',
    title: 'Sound Match',
    description: 'Match Malayalam words to their correct pronunciations.',
    href: '/play?id=sound-match',
    prerequisite: 'voice-command-game',
  },
  {
    id: 'speed-typing',
    title: 'Speed Typing Race',
    description: 'Type Malayalam words quickly before the timer runs out.',
    href: '/play?id=speed-typing',
    prerequisite: 'sound-match',
  },
  {
    id: 'emoji-word-match',
    title: 'Emoji-to-Word Match',
    description: 'Match emojis with their corresponding Malayalam words.',
    href: '/play?id=emoji-word-match',
    prerequisite: 'speed-typing',
  },
  {
    id: 'fill-in-the-blanks',
    title: 'Fill in the Blanks',
    description: 'Complete Malayalam sentences by filling in the missing words.',
    href: '/play?id=fill-in-the-blanks',
    prerequisite: 'emoji-word-match',
  },
  {
    id: 'quiz-battle',
    title: 'Quiz Battle',
    description: 'Challenge your friends in a head-to-head Malayalam knowledge quiz.',
    href: '/play?id=quiz-battle',
    prerequisite: 'fill-in-the-blanks',
  },
  {
    id: 'festival-quest',
    title: 'Festival Quest',
    description: 'Explore Malayalam festivals and traditions through interactive quests.',
    href: '/play?id=festival-quest',
    prerequisite: 'quiz-battle',
  },
  {
    id: 'cultural-trivia',
    title: 'Cultural Trivia Show',
    description: 'Test your knowledge of Malayalam culture in a quiz show format.',
    href: '/play?id=cultural-trivia',
    prerequisite: 'festival-quest',
  },
  {
    id: 'word-search',
    title: 'Word Search',
    description: 'Find hidden Malayalam words in a grid of letters.',
    href: '/play?id=word-search',
    prerequisite: 'cultural-trivia',
  },
  {
    id: 'crossword-puzzle',
    title: 'Crossword Puzzle',
    description: 'Solve Malayalam crossword puzzles.',
    href: '/play?id=crossword-puzzle',
    prerequisite: 'word-search',
  },
  {
    id: 'malayalam-scrabble',
    title: 'Malayalam Scrabble',
    description: 'Play Scrabble with Malayalam letters.',
    href: '/play?id=malayalam-scrabble',
    prerequisite: 'crossword-puzzle',
  },
  {
    id: 'wordfind',
    title: 'WordFind',
    description: 'Find Malayalam words in a 6x6 grid using a clock dial letter selection.',
    href: '/play?id=wordfind',
    prerequisite: 'malayalam-scrabble',
  },
  {
    id: 'spin-a-wheel',
    title: 'Spin a Wheel',
    description: 'Test your luck and learn consonants with a spin of the wheel.',
    href: '/games/spin-a-wheel',
    prerequisite: 'wordfind',
  },
  {
    id: 'consonant-arrow-game',
    title: 'Consonant Arrow Game',
    description: 'Aim and shoot consonants with a bow and arrow.',
    href: '/play?id=consonant-arrow-game',
    prerequisite: 'spin-a-wheel',
  },
];